src/account.js
src/index.js
src/messages.js
src/utilities.js

This PR handles the case where two events are fired for one transaction due to a websocket watching via a hash and address.
closes #10

Handle watch address changes

---

src/index.ts
src/interfaces.ts
src/messages.ts
src/transaction.ts

This PR makes some changes to the payload for each transaction event so that it matches (as closely as possible) the payload that our [Notify API](https://docs.blocknative.com/webhook-api) sends.
The following parameters have been **added**  to the transaction payload:
`serverVersion` - version of the server that sent the payload (`String`)
`timeStamp` - time stamp of when the server sent the payload (`String`)
`system` - system (blockchain) the transaction occurred on (`String`)
`network` - network name the transaction occurred on (`String`)
The following parameters in the transaction payload have been **modified**:
`originalHash` - has been replaced with `replaceHash`
`status` - speedup and cancel events were both represented with a status of `'pending'`, in this update they will be …

Enhancement: Match webhook api

---

package.json
src/config.ts
src/index.ts
src/interfaces.ts
src/messages.ts
src/utilities.ts

This update adds a message queue for event logs that are sent to the Blocknative server. The queue improves performance and correctly handles rate limits, preventing dropped messages.
When the SDK receives a call to send an event to the server, the event log will get pushed to the end of the `queuedMessages` queue. If the queue isn't currently being processed, then it will start processing event logs.
During processing, an event log will be pulled from the front of the queue and then before sending to the server, it will check whether it needs to wait for some period of time to stay within rate limits that have been enforced by the server.
Once it has looped through and sent all messages in the queue, it will reset the rate limits to the default and finish processing.

Hotfix: Rate limit messages based on server response

---

package.json
src/index.ts
src/interfaces.ts
src/messages.ts
src/validation.ts

- Adds optional `appVersion` parameter to SDK initialization to log Onboard and Notify versions
- Sends `appName` and `appVersion` with all messages to server

3.0.0-0.1.0: Add appVersion and appName to WS messages

---

package.json
src/messages.ts

- Fixes bug where the transaction hash of a replaced transaction was not getting matched and replaced with the new transaction hash.
Fixes (#122)

3.3.2-0.0.1: [fix] -Transaction Replace Status Emitter

---

package.json
src/messages.ts

The emitter result from the account emitter was being ignored due to the fact that the configuration being undefined was not taken into account.
Fixes notify.js issue blocknative/notify#189

3.3.3-0.0.1: [fix] account emitter

---

package.json
src/index.ts

Increases the default WebSocket `connectTimeout` from `5000` to `10000`

3.5.0-0.1.0: [enhancement] - Connect Timeout

---

package.json
src/messages.ts

This PR fixes a bug where the transaction hash on a replacement transaction would be the new transaction, but the rest of the payload would match the original transaction that has been replaced. This is a breaking change that fixes the payload and matches the behaviour of our Webhook notifications.

3.7.1-1.0.0: [fix] - Replacement Transactions

---

package.json
src/defaults.ts
src/interfaces.ts

Add fantom network (fantom-main) to Network type in interfaces.ts and networks object in defaults.ts

4.0.0-0.1.0 : [feature] - Add fantom network

---

src/index.ts
src/messages.ts
src/utilities.ts

Fixes #171. 
This PR adds a utility function that tests whether `window.localStorage` is available and accessible (writeable/readable) before performing operations.

Test whether localStorage is accessible before performing operations

---

package.json
yarn.lock

- added simulation public handler
- added a new dependency (nano id) so the SDK can identify roundtrip WS requests

DEVELOP - Release/4.2.0

---

package.json
src/messages.ts

This PR introduces an error message when bn-server sends back the `UNSUPPORTED_CHAIN_MSG`. The message is received when the requested `networkId` is not allowed by the users tier. The websocket will close and an error message is returned (introduced in this PR https://github.com/blocknative/bn-server/pull/1273)
This PR also moves the `simulation` error handling further down the file so that unhandled error messages do not get caught at an undefined `event` object. 
Prior to this fix, the SDK will just fail here
```    
if (event.categoryCode === 'simulate') {
simulations$.error(event)
return
}
```
With the fix, end users will see a user friendly error message.

4.2.0-0.1.0 [Feature] Error Handling for UNSUPPORTED_CHAIN_MSG

---

package.json
src/defaults.ts
src/interfaces.ts

adds support for mumbai testnet
ran npm test to test feature works, I also followed a related PR for Matic Main to enable this so feel the change is low risk.

4.2.0-0.1.0 [ feature ] : Mumbai testnet support

---

package.json
src/account.ts
src/configuration.ts
src/index.ts
src/interfaces.ts
src/messages.ts
src/simulate.ts
src/transaction.ts
src/unsubscribe.ts

This PR:
- Exposes the lists of watched items (`watchedTransactions`, `watchedAccounts`, `configurations`) to the public API rather than having them marked as private.
- Fixes types so that `this` refers to the `Blocknative` class rather than `any`
These changes are needed to be able to create a multi-chain SDK that automatically closes connections if there are no longer any subscriptions associated with that connection.

4.2.0-0.2.0: [enhancement] - Expose Watched Items

---

package.json
src/index.ts
src/multichain/index.ts
src/types.ts
src/validation.ts

The Blocknative server now allows authentication with an API key as a query parameter in the initial http upgrade request rather than needing to pass the API key as the `dappId` parameter within the initial message. This can be useful in the case of using a WebSocket proxy to hide the API key.
This PR changes the types so that the either a `dappId` or a `apiUrl` needs to be passed in to initialization and assumes that the API key is included in the `apiUrl` as a query parameter.

4.5.0-0.1.0: [feature] -  Optional dappId when apiUrl

---

package.json
src/index.ts
src/multichain/index.ts
src/types.ts
src/validation.ts

- Makes `dappId` optional when using `apiUrl`

Release 4.6.0

---

package.json

Update types and usage for MultiSim
Remove unsupported chains

Release 4.6.1 (develop)

---

package.json
src/defaults.ts
src/types.ts
src/validation.ts

This PR reverts the changes for dropping unsupported chains as that needs to be released when the chains are dropped from the Blocknative server.

Revert: Dropping Chains

---

package.json
src/defaults.ts
src/types.ts
src/validation.ts

- Deprecates Bitcoin, Kovan, BNB and Fantom chains that will no longer be supported by the Blocknative server

4.6.2-0.0.1: Deprecate Unsupported Chains

---

package.json
src/defaults.ts
src/types.ts

- Deprecates Rinkeby and Ropsten networks as they are no longer supported by the Blocknative server

4.6.3-0.0.1 - Update: Deprecate Rinkeby and Ropsten networks

---

package.json
src/types.ts

- Fixes incorrect `gasUsed` parameter (fixes #219)
- Adds missing `Status` and corrects simulation status (fixes #220)

4.6.3-0.0.2 - Fix: Incorrect Types

---

package.json
src/types.ts

The `'simulated'` Status type was missing and is used by the Transaction Preview package. This error was found with the addition of new type checks in our W3O publishing pipeline.

[4.6.4-0.0.1]: Fix - Add 'simulated' type to Status

---

package.json

Bug fix for:  'simulated' Status type was missing and is used by the Transaction Preview package. This error was found with the addition of new type checks in our W3O publishing pipeline.

Release 4.6.5 (develop)

---

package.json
src/types.ts

Bug fix for:  'simulated' Status type was missing and is used by the Transaction Preview package. This error was found with the addition of new type checks in our W3O publishing pipeline.

Release 4.6.5 (master)

---

package.json
src/types.ts

Add missing types for sim response
```typescript
export interface ContractCall {
contractType?: string
contractAddress?: string
contractAlias?: string
methodName: string
params: Record<string, unknown>
contractName?: string
contractDecimals?: number
decimalValue?: string
}
export interface InternalTransaction {
type: string
from: string
to: string
input: string
gas: number
gasUsed: number
value: string
contractCall: ContractCall
error?: string
errorReason?: string
}
```

[4.6.5-0.0.1] : Update - Add missing types for sim response
