blocknative/sdk

src/messages.js, src/transaction.js, src/utilities.js
=> Change to emit pattern for events

src/utilities.js
=> Return value from emit call

package.json, src/state.js, types.d.ts
=> Add typescript definitions

package.json, src/interfaces.ts
=> Release 0.2.3

src/account.ts, src/interfaces.ts, src/transaction.ts
=> Revert "Set default clientIndex value"

src/bnc-sdk.ts, src/interfaces.ts, src/messages.ts, src/transaction.ts, src/unsubscribe.ts, src/utilities.ts, src/validation.ts
Still needs to be tested with the back-end to make sure it is working correctly.
=> Feature: Add unsubscribe method to API

package.json, src/interfaces.ts
=> Add more detail to NotificationObject type (#72)

src/interfaces.ts, src/utilities.ts
- Adds `off` method to the event emitter to be able to remove a listener that was registered for an event
=> Enhancement: Event Emitter off Method

package.json, src/interfaces.ts, src/utilities.ts
- Adds missing event codes in the Emitter validation switch block and updates docs link
=> 3.1.0-0.0.1: [fix] - Add Event Codes

package.json
=> Version 3.1.1

package.json, src/defaults.ts, src/interfaces.ts
- Adds support for Binance Smart Chain
=> 3.1.1-0.1.0: [feature] - Binance Smart Chain Support

package.json, src/interfaces.ts, src/utilities.ts
- Adds Binance Smart Chain support
=> Release 3.2.0

package.json
- Syncs develop branch with new release
=> Version 3.2.0

package.json, src/interfaces.ts, src/utilities.ts
- Adds new `txPoolSimulation` `eventCode` for listening to simulated pending events on an emitter
=> 3.2.0-0.1.0: [feature] - Pending Simulation Event Code

package.json
=> Version 3.3.0

package.json, src/interfaces.ts, src/utilities.ts
- Adds `txPoolSimulation` eventCode
=> Release 3.3.0

package.json, src/configuration.ts, src/messages.ts
=> 3.3.0-0.0.1: [fix] - Ensure Correct Casing for Config Scope

package.json
=> Release 3.3.1

package.json
=> Version 3.3.2

package.json, src/messages.ts, yarn.lock
- Modifies ratelimit error handling to handle sim and regular event limits
- Updates dependency due to security notification
=> Release 3.3.2

package.json, src/configuration.ts, src/messages.ts
Fix so that server errors regarding invalid configurations are correctly passed on to the client.
Fixes #134
=> 3.4.0-0.0.1: [fix] - Config Error

package.json
=> Release 3.4.1

package.json, src/defaults.ts, src/interfaces.ts
- Adds Matic main network to the list of valid networks to monitor
=> 3.4.1-0.1.0: [feature] - Matic Main Network

package.json, src/interfaces.ts
- Fixes types for `internalTransactions` and `netBalanceChanges` fields on Ethereum transaction payloads
Fixes #138
=> 3.4.1-0.1.1: [fix] - Eth Transaction Types

package.json, yarn.lock
- Updates dependencies to address security alerts
=> 3.4.1-0.1.2: [chore] - Update Deps

package.json, pull_request_template.md, src/defaults.ts, src/interfaces.ts, yarn.lock
- Adds Polygon Matic network support
- Fixes transaction types
- Adds PR template checklist
=> Release 3.5.0

package.json
=> Release 3.6.0

package.json, src/interfaces.ts, src/messages.ts
- Adds `dispatchTimestamp` field to transaction payloads
=> 3.6.0-0.1.0: [enhancement] - Add Dispatch Timestamp

package.json
=> Release 3.7.0

README.md
closes: #158 
Provide working examples for the readme
- [x ] I tested locally to make sure this feature/fix works
=> 158: Provide working example for the README

README.md, package.json, src/index.ts
- Updates readme quickstarts
- Bugfix: Check for WS before registering for events
=> Release 3.7.1

package.json, src/interfaces.ts
- Add Fantom network support 
- Refactor and refine check for localStorage usability
=> 4.1.0 Release - Develop

package.json, src/defaults.ts, src/index.ts, src/interfaces.ts, src/messages.ts, src/utilities.ts
- Add Fantom network support 
- Refactor and refine check for localstorage usability
=> 4.1.0 Release - Master

.circleci/config.yml, README.md, package.json, src/defaults.ts, src/index.ts, src/interfaces.ts, src/messages.ts, src/simulate.ts, src/streams.ts, src/utilities.ts, yarn.lock
- Adds support for mumbai testnet, a member of the polygon/matic family.
- error handling for unsupported chain msg + move simulation error check down
=> Release 4.3.0 [master]

package.json
=> Version 4.4.0 (develop)

README.md, package.json
=> Release 4.4.1 (develop)

README.md, package.json, src/index.ts, src/messages.ts, src/multi-sim.ts, src/streams.ts, src/types.ts
- Adds multisim method for simulating multiple transactions at once.
=> Release 4.5.0 (main)

package.json
=> Release 4.5.0 (develop)

package.json
=> Release 4.6.0

package.json, src/configuration.ts, src/multichain/subscribe.ts, src/types.ts
- Fixes some optional types
- Fixes parameter destructuring and default for ABI
=> 4.6.0-0.0.1: [fix] - Types and Params

README.md, package.json, src/configuration.ts, src/defaults.ts, src/multi-sim.ts, src/multichain/subscribe.ts, src/streams.ts, src/types.ts, src/validation.ts, yarn.lock
Update types and usage for MultiSim + Docs for usage
Remove unsupported chains
=> Release 4.6.1 (master)

package.json
=> Release 4.6.2

package.json, src/defaults.ts, src/types.ts, src/validation.ts
Removes deprecated chains.
Changelog:
- 4.6.2-0.0.1: Deprecate Unsupported Chains #215
=> Release 4.6.3 (master)

package.json
=> Release 4.6.3 (develop)

package.json
=> Release 4.6.4

package.json, src/types.ts
This release includes expanded type coverage for sim response
=> Release 4.6.6 

package.json
This release includes expanded type coverage for sim response
=> Release 4.6.6 (develop)

package.json, src/types.ts
=> [4.6.6-0.0.1] Fix - Add missing Sim types

package.json, src/types.ts
This release includes enhancements to the MultiSim output types
=> Release 4.6.7

package.json
This release includes enhancements to the MultiSim output types
=> Release 4.6.7 (develop)

package.json, src/defaults.ts
This release add sepolia to networks
=> Release 4.6.8 (develop)

package.json, src/defaults.ts, src/types.ts
This release add sepolia to networks
=> Release 4.6.8

.circleci/config.yml
=> update .circleci/config.yml image

package.json, src/defaults.ts, src/types.ts
remove depreciated chains Goerli and Mumbai
=> 4.6.8-0.0.1 [UPDATE] Remove Goerli and Mumbai

package.json, src/defaults.ts, src/types.ts
=> 4.6.8-0.0.2 [ENH] add amoy
